In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

import tensorflow as tf
tf.enable_eager_execution()

/home/malzantot/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/malzantot/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/malzantot/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/malzantot/anaconda3/lib/python3.6/site-packages/tensorflow/python/f

In [2]:
from syn_dataset import SynDataset
from data_utils import DataFactory

W0809 20:35:11.402951 139727244351296 deprecation_wrapper.py:119] From /home/malzantot/Nesl/bio_gan/ecg_dataset.py:13: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.



In [6]:
dataset_name = 'ecg'
fake_data = [
    ('samples/ecg_crnn/08_01_22_13', 'CRNN'),
    ('samples/ecg_crvae/07_29_13_10', 'CVRAE'),
    ('samples/ecg_rgan/07_30_22_02', 'CRGAN'),
    ('samples/ecg_rganar/07_30_22_03', 'CRGAN-AR'),
    ('samples/ecg_physgan/07_27_21_11', 'PhisyoGAN'),
    
]

In [7]:
def plot_samples(dset_name, fake_result, plots_per_class = 1, row_width=4, fontsize=24):
    real_train, real_test, metadata = DataFactory.create_dataset(dataset_name)
    real_data = real_test.shuffle(1000).batch(100)
    fake_data = [SynDataset(fake_path).to_dataset().shuffle(1000).batch(100) for fake_path, fake_name in fake_result]
    
    
    num_cols = metadata.num_labels * plots_per_class
    num_rows = len(fake_result)+1
    
    all_data = [real_data] + fake_data
    fig, axes = plt.subplots(num_rows, num_cols, figsize=(num_cols*row_width, (num_rows*row_width)))
    for i in range(num_rows):
        batch_x, batch_y = next(iter(all_data[i]))
        batch_x = batch_x.numpy()
        batch_y = batch_y.numpy()
        #cur_color = 'b' if i == 0 else 'r'
        for j in range(metadata.num_labels):
            cur_idx = 0
            for k in range(plots_per_class):
                cur_col = j*plots_per_class+k
                while (batch_y[cur_idx] != j):
                    cur_idx += 1
                axes[i][cur_col].plot(batch_x[cur_idx,:,:])
                #axes[i][cur_col].set_title('{}'.format(cur_idx))
                cur_idx += 1
                axes[i][cur_col].set_ylim(-0.25, 0.35)
                #axes[i][cur_col].set_yticks([])
                #axes[i][cur_col].set_xticks([])
                
                if cur_col == 0:
                    if i == 0:
                        axes[i][cur_col].set_ylabel('Real', fontsize=fontsize)                        
                    else:
                        axes[i][cur_col].set_ylabel(fake_result[i-1][1], fontsize=fontsize)

                if i == 0:
                    axes[i][cur_col].set_title(metadata.class_names[j], fontsize=fontsize)
                    
    plt.tight_layout()
    return fig



In [8]:
fig = plot_samples(dataset_name, fake_data, plots_per_class=3)
fig.savefig('ecg_result.png')

['1 NSR', '4 AFIB']
['1 NSR', '4 AFIB']
(array([0, 1], dtype=int32), array([211, 102]))
['1 NSR', '4 AFIB']
['1 NSR', '4 AFIB']
(array([0, 1], dtype=int32), array([72, 33]))


In [9]:
dataset_name = 'ecg'
fake_data = [
    ('samples/ecg_physgan/07_27_21_11', 'PhisyoGAN'),
]
fig = plot_samples(dataset_name, fake_data, plots_per_class=3)
fig.savefig('ecg_result_main.png')

['1 NSR', '4 AFIB']
['1 NSR', '4 AFIB']
(array([0, 1], dtype=int32), array([211, 102]))
['1 NSR', '4 AFIB']
['1 NSR', '4 AFIB']
(array([0, 1], dtype=int32), array([72, 33]))
